language: node_js
node_js:
    - "10"
stages:
  - test
  - name: documentation
    if: branch = main AND type != pull_request
  - name: npm_deploy
    if: branch = main OR branch = develop
jobs:
  include:
    - stage: test
      script:
      - npm run typecheck
      - npm run lint
      - npm run test
      - npm run codecov
    - stage: documentation
      script:
        - npm run build
        - touch ./styleguide/.nojekyll
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: ./styleguide
        skip_cleanup: true
        target_branch: gh-pages
        on:
          branch: main
    - stage: npm_deploy
      before_deploy: "./.travis_version_bump.sh"
      deploy:
        provider: npm
        email: $DEV_TEAM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        tag: $NPM_TAG
