language: node_js
node_js:
    - "10"
stages:
  - test
  - name: documentation
    if: branch = master AND type != pull_request
  - name: version_bump 
    if: (branch = master OR branch = develop) AND type != pull_request
  - name: npm_publish 
    if: (branch = master OR branch = develop) AND type != pull_request
jobs:
  include:
    - stage: test
      script:
      - npm run typecheck
      - npm run lint
      - npm run test
      - npm run codecov
    - stage: documentation
      script:
        - npm run build
        - touch ./styleguide/.nojekyll
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: ./styleguide
        target_branch: gh-pages
        on:
          branch: master
    - stage: version_bump
      script: "./.travis_version_bump.sh"
      on: 
        tags: false
    - stage: npm_publish
      before_deploy: '[[ $TRAVIS_BRANCH == master ]] && NPM_TAG = latest || NPM_TAG = develop'
      deploy:
        provider: npm
        email: $DEV_TEAM_EMAIL 
        api_key: $NPM_TOKEN
        tag: $NPM_TAG
        on:
          tags: true
