language: node_js
node_js:
    - "10"
stages:
  - test
  - name: documentation
    if: branch = master AND type != pull_request
  - name: npm_deploy_develop
    if: branch = develop AND type != pull_request
jobs:
  include:
    - stage: test
      script:
      - npm run typecheck
      - npm run lint
      - npm run test
      - npm run codecov
    - stage: documentation
      script:
        - npm run build
        - touch ./styleguide/.nojekyll
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: ./styleguide
        target_branch: gh-pages
        on:
          branch: master
    - stage: npm_deploy_develop
      before_deploy: "./.travis_version_bump.sh"
      deploy:
        provider: npm
        email: $DEV_TEAM_EMAIL 
        api_key: $NPM_TOKEN
        tag: develop
